apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cli-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cli
  template:
    metadata:
      labels:
        app: api-cli
    spec:
      containers:
        - image: gcr.io/peachtree/peachtree-services-api-cli
          imagePullPolicy: Always
          name: api-cli
          # resources:
          #   limits:
          #     cpu: "1000m"
          #     memory: "4Gi"
          env:
            - name: ENV_NAME
              value: "production"
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/peachtree_production"
            - name: APP_URL
              value: "https://ptre.dev"
            - name: ADMIN_EMAIL
              value: "admin@ptre.dev"
            - name: ADMIN_PASSWORD
              value: "development.now"
            - name: POSTMARK_FROM
              value: "no-reply@ptre.dev"
            - name: UPLOADS_STORE
              value: "gcs"
            - name: UPLOADS_GCS_BUCKET
              value: "peachtree-production-uploads"
            # The `bedrock cloud` command in the CLI will help with
            # the creation and storing of secrets for production.
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_SECRET
            - name: POSTMARK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTMARK_API_KEY
