apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cli-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cli
  template:
    metadata:
      labels:
        app: api-cli
    spec:
      containers:
        - image: gcr.io/peachtree/peachtree-services-api-cli
          imagePullPolicy: Always
          name: api-cli
          # resources:
          #   limits:
          #     cpu: "1000m"
          #     memory: "4Gi"
          env:
            - name: ENV_NAME
              value: "staging"
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/peachtree_staging"
            - name: APP_URL
              value: "https://ptre.dev"
            - name: POSTMARK_FROM
              value: "no-reply@ptre.dev"
            - name: POSTMARK_API_KEY
              value: "abc"
            - name: UPLOADS_STORE
              value: "gcs"
            - name: UPLOADS_GCS_BUCKET
              value: "peachtree-staging-uploads"
